version: '3.9'
services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management
        command: rabbitmq-server
        ports:
          - 5672:5672
          - 15672:15672
        healthcheck:
          test: rabbitmq-diagnostics -q ping
          interval: 30s
          timeout: 30s
          retries: 2
        environment:
          - RABBITMQ_DEFAULT_USER=ad
          - RABBITMQ_DEFAULT_PASS=12345678!Ad
        depends_on:
            - db
    api-gateway:
        container_name: api-gateway-service
        build:
            context: api-gateway
            dockerfile: /docker/dev/Dockerfile
        image: api-gateway:latest
        ports:
            - 8080:8080
        restart: on-failure
    account:
        container_name: account-service
        build:
            context: account
            dockerfile: /docker/dev/Dockerfile
        image: account-service:latest
        ports:
            - 8081:8081
        restart: on-failure
        depends_on:
            rabbitmq:
              condition: service_healthy
    product:
        container_name: product-service
        build:
            context: product
            dockerfile: /docker/dev/Dockerfile
        image: product-service:latest
        ports:
            - 8082:8082
        restart: on-failure
        depends_on:            
            rabbitmq:
              condition: service_healthy
    db:
        container_name: db
        image: postgres:14.1-alpine
        restart: always
        environment:
          - POSTGRES_PASSWORD=123456
        ports:
          - '5432:5432'
        volumes: 
          - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
