jwt:
  secret: 12345678@Ab!
spring:
  application:
    name: api-gateway
  profiles:
    active: local
gateway:
  host: http://localhost
--- 
spring:
  config:
    activate:
      on-profile: dev
gateway:
  host: http://host.docker.internal